// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://favzfivkpfdzgkbutuji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdnpmaXZrcGZkemdrYnV0dWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTIwNzEsImV4cCI6MjA1MzM2ODA3MX0.G2W2pWkbi76u36ZQf4KVjHD1I1JKpO1CkNTuzJWH2Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);